<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <!-- <link name="gripper_tool_link" /> -->
    <xacro:cylinder_shape link_name="gripper_base" m="${gripper_mass}" r="${gripper_rad}" l="${gripper_len}" o_xyz="0 0 0" o_rpy="0 0 0" color="grey"/>

    <xacro:box_shape link_name="gripper_left" m="${gripper_mass}" x="${gripper_finger_len}" y="${gripper_finger_wid}" z="${gripper_finger_hei}" o_xyz="0 0 0" o_rpy="0 0 0" />
    <xacro:box_shape link_name="gripper_right" m="${gripper_mass}" x="${gripper_finger_len}" y="${gripper_finger_wid}" z="${gripper_finger_hei}" o_xyz="0 0 0" o_rpy="0 0 0" />

    <!-- wrist to gripper base -->
    <joint name="wrist_gripper_base" type="fixed">
        <origin xyz="0.0 0.0 ${gripper_rad}" rpy="${pi/2} 0.0 0.0"/>
        <parent link="tool_link"/>
        <child link="gripper_base"/>
    </joint>

    
    
    <joint name="gripper_base_gripper_left" type="prismatic">
        <origin xyz="0.0 ${(gripper_len + gripper_rad)/ 2 } -${(gripper_len + gripper_rad)/ 2 }" rpy="${pi/2} 0.0 0.0"/>
        <parent link="gripper_base"/>
        <child link="gripper_left"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit lower="0.0" upper="${gripper_len / 2 - static_rad / 2}" effort="100.0" velocity="0.1"/>
    </joint>

    <joint name="gripper_base_gripper_right" type="prismatic">
        <origin xyz="0.0 ${(gripper_len + gripper_rad)/ 2 } ${(gripper_len + gripper_rad)/ 2 }" rpy="${3*pi/2} 0.0 0.0"/>
        <parent link="gripper_base"/>
        <child link="gripper_right"/>
        <axis xyz="0.0 1.0 0.0"/>
        <mimic joint="gripper_base_gripper_left" multiplier="1.0" />
        <limit lower="0.0" upper="${gripper_len / 2 - static_rad / 2}" effort="100.0" velocity="0.1"/>
    </joint>
</robot>